FROM python:3.9-slim-buster

COPY . .

RUN python -m venv venv
RUN chmod +x venv/bin/activate
RUN venv/bin/activate

RUN pip install -r ./requirements.txt

EXPOSE 8000
WORKDIR /src
CMD [ "python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload" ]
