services:
  backend:
    build: './Backend/zenya-form-prototype-backend/'
    ports:
      - "8000:8000"
    environment:
      - FRONTEND_URL=http://localhost
      - MODEL_URL=http://localhost:8001
  
  frontend: 
    build: './Frontend/'
    ports:
      - "80:80"
    environment:
     - REACT_APP_API_URL=http://localhost:8000
  
  models:
    build: './Models'
    ports:
      - "8001:8000"
