FROM node:14 AS build

COPY package.json ./
RUN yarn install
COPY . .
RUN yarn build && rm -rf node_modules

FROM nginx:1.19.0-alpine AS production
COPY --from=build /build /usr/share/nginx/html
EXPOSE 80
CMD [ "nginx", "-g", "daemon off;" ]
